#env = Environment(CPPPATH = ['../v8/include']);

Program('exam_01', 'main.cc', LIBS=['v8', 'pthread'], LIBPATH='/home/tsaicw/workspace/open_source/v8', CPPPATH=['/home/tsaicw/workspace/open_source/v8/include']);

